<?php
	$this->headTitle(_('Manage Users'));
	$this->headScript()->appendFile(URL . 'js/admin/adminGrid.js?v=2015110401')
					->appendFile($this->basePath() . '/js/admin/chosen.jquery.js', 'text/javascript')
					->appendFile($this->basePath() . '/js/changeabledata-checkbox.js')
					->appendFile(URL . 'js/admin/pages/user.js')
					->appendFile(URL . 'js/tools/jquery-ui-1.10.4.custom.min.js')
	;
	$this->headLink()->prependStylesheet($this->basePath() . '/css/admin/chosen.css')
					->prependStylesheet(URL . 'css/tools/ui/jquery-ui-1.10.4.custom.css')
;
?>

<div class="clear"></div>
<div id="gridbox"></div>
<div style="display:none">
	<div id="pid_flt_box"><input class="js-filter-value" onkeyup="adminGrid.filterBy()"></div>
	<div id="name_flt_box"><input class="js-filter-value" onkeyup="adminGrid.filterBy()"></div>
	<div id="email_flt_box"><input class="js-filter-value" onkeyup="adminGrid.filterBy()"></div>
	<div id="role_flt_box">
	<?php
		$roles = \Application\Model\UserTable::$roleDescriptions;
		array_unshift($roles, 'All');
		?>
		<select class="chosen-select js-filter-value" onchange="adminGrid.filterBy()">
			<?php foreach ($roles as $value=>$role){?>
				<option value="<?php echo $value;?>"><?php echo $role;?></option>
			<?php }?>
		</select>
	</div>
	<div id="status_flt_box">
		<select class="chosen-select js-filter-value" onchange="adminGrid.filterBy()">
			<option value="-1"><?php echo _('All');?></option>
			<option value="1"><?php echo _('Active');?></option>
			<option value="0"><?php echo _('Inactive');?></option>
		</select>
	</div>
</div>
<div id="date_flt_box">
	<div  class="clearfix">
		<div class="singleDP">
			<input id="created" readonly="readonly" onchange="adminGrid.filterBy()">
		</div>
		<div class="rangeDP">
			<input id="created_from" readonly="readonly"  style="width:46%" onchange="adminGrid.filterBy()">-
			<input id="created_to" readonly="readonly"  style="width:46%" onchange="adminGrid.filterBy()">
		</div>
		<a href="javascript:void(0);" class="clearDate" onclick="common.clearDate(this); return false;">&nbsp;</a>
	</div>
	<p class="showDatepickersWrapp">
		<?php echo _('Date') ?>
		<span class="datepickersToggle showDatepickersLeft" onclick="common.toggleCustomDatepicker(this);"> </span>
		<?php echo _('Date Range') ?>
	</p>
</div>
<script>
	$(function() {
		$("#created").datepicker({
			"dateFormat": 'dd.mm.yy',
			changeMonth: true,
			changeYear: true,
			maxDate: 0,
			onClose: function( selectedDate ) {
				$("#created_from").val("");
				$("#created_to").val("");
				$("#endActive").datepicker( "option", "minDate", selectedDate);}
		});
		$("#created_to").datepicker({
			"dateFormat": 'dd.mm.yy',
			changeMonth: true,
			changeYear: true,
			maxDate: 0,
			onClose: function( selectedDate ) {
				$("#created").val("");
				$("#created_from").datepicker( "option", "maxDate", selectedDate);}
		});
		$("#created_from").datepicker({
			"dateFormat": 'dd.mm.yy',
			changeMonth: true,
			changeYear: true,
			maxDate: 0,
			onClose: function( selectedDate ) {
				$("#created").val("");
				$("#created_to").datepicker( "option", "minDate", selectedDate);}
		});
	});

	var gridColumns = [
		{'title' : "#", 'width': 30},
		{'title' : <?php echo json_encode(_('User ID'));?>, 'width': 85, 'colSorting': 'int', 
			'filter': {
				'sourceContainerSelector': "#pid_flt_box",
				'values': [{'name':'flPid'}]
			}
		},
		{'title' : <?php echo json_encode(_('Name'));?>, 'width': 120, 'colSorting': 'str', 
			'filter': {
				'sourceContainerSelector': "#name_flt_box",
				'values': [{'name':'flName'}]
			}
		},
		{'title' : <?php echo json_encode(_('Email'));?>, 'width': 120, 'colSorting': 'str', 
			'filter': {
				'sourceContainerSelector': "#email_flt_box",
				'values': [{'name':'flEmail'}]
			}
		},
		{'title' : <?php echo json_encode(_('User Type'));?>, 'width': 100, 
			'filter': {
				'sourceContainerSelector': "#role_flt_box",
				'values': [{'name':'flRole'}]
			}
		},
		{'title' : <?php echo json_encode(_('Status'));?>, 'width': 70, 
			'filter': {
				'sourceContainerSelector': "#status_flt_box",
				'values': [{'name':'flStatus'}]
			}
		},
		{'title' : <?php echo json_encode(_('Registration date'));?>, 'width': 80, 
			'filter': {
				'sourceContainerSelector': "#date_flt_box",
				'values': [
					{'name':'flCreated', 'fieldSelector': '#created'}, 
					{'name':'flCreatedFrom', 'fieldSelector': '#created_from'}, 
					{'name': 'flCreatedTo', 'fieldSelector': '#created_to'}
				]
			}
		},
		{'title' : <?php echo json_encode(_('Actions'));?>, 'width': <?php echo ($canDelete)? '30' : '60';?>}
	];
	<?php if ($canDelete) {?>
		gridColumns.push({
			'title' : "#cspan", 'width': 30
		});
	<?php } ?>

	$(document).ready(function(){ 
		adminGrid.init({
			listUrl: <?php echo json_encode($this->basePath('admin/user/list'));?>+"?action=list",
			columns: gridColumns,
			events: [
				{
					'name': "onBeforeSelect", 'callback': function(id,ind){
						var rowNum = adminGrid.grid.cellById(id,0).getValue();
						return common.selectItemInList(id, rowNum, <?=json_encode($this->basePath('admin/user/edit/'));?>, true);
					}
				}
			]
		});

		$(".chosen-select").chosen({disable_search_threshold: 7});
	});
</script>
