<?php
use Application\Lib\Time;
header("Content-Type: text/json");
$i = $pos;
$data = ['rows' => []];
foreach ($list as $item) {
	$i++;
	$editActions = "<a class='edit' onclick='getUserEditForm(".$item->id.")' >" . _("Edit") . "</a> ";
	if ($isAllowedDelete)
			$deleteActions = "<a class='del' href='javascript:void(0);' onclick='common.confdel(\"".URL."admin/user/delete/\",{$item->id}, common.removeItem); (arguments[0]||window.event).cancelBubble=true; return false;'>"._('Delete')."</a>";
	$row = [
			$i,
			$item->id,
			htmlspecialchars($item->name),
			htmlspecialchars($item->email),
			htmlspecialchars(\Application\Model\UserTable::$roleDescriptions[$item->level]),
			(($item->active)? 'Active' : 'Inactive'), 
			htmlspecialchars(Time::formatDate($item->created, Time::FORMAT_SHORT)),
			$editActions, 
			(($deleteActions)? $deleteActions : '' ),
	];
	$data['rows'][] = [
			'id' => $item->id,
			'data' => $row,
	];
}
echo json_encode($data);
