<?php 
$this->headTitle(_('Edit Email Template'));
$this->headScript()->appendFile($this->basePath(). '/js/tiny_mce/tiny_mce_src.js')
->appendFile($this->basePath(). '/js/admin/pages/content-version.js')
;
?>
<div class="temlates">
	<?php
	if (isset($error) && !empty($error)){
		echo $error;
		return;
	}
	if (isset($langs)){ ?>
		<ul class='tabs-horiz clearfix' id='invTabsUl'>
			<?php foreach ($langs as $i => $lang) { ?>
				<li><a class='tab-item-link invTabs<?php echo $lang['id'];?> <?= ($lang['id'] == $activeLang) ? 'active' : '' ?>' onclick='return common.changeLang(<?= $lang['id']; ?>, "invTabs");' href='#'><span><?= $lang['name']; ?></span></a></li>
				<?php } ?>
		</ul>
	<?php }?>
	<div class="invTabs">
		<?php echo $this->form()->openTag($form) ?>
		<?php echo $this->wrappedElement($form->get('csrf')); ?>
		<?php echo $this->wrappedElement($form->get('id')); ?>
		<?php echo $this->wrappedElement($form->get('updated')); ?>
		<div class="formRow clearfix">
			<?php echo $this->wrappedElement($form->get('name')); ?>
		</div>
		<?php foreach ($langs as $lang) { ?>
			<div class="formRow clearfix">
				<?php echo $this->wrappedElement($form->get('subject[' . $lang['id'] . ']')); ?>
			</div>
			<div class="formRow clearfix">
				<?php echo $this->wrappedElement($form->get('text[' . $lang['id'] . ']')); ?>
			</div>
		<?php } ?>

		<div class="clearfix btnsWrapp">
			<?php echo $this->wrappedElement($form->get('submit')); ?>
			<?php echo $this->wrappedElement($form->get('cancel')); ?>
		</div>
		<?php echo $this->form()->closeTag($form); ?>
	</div>
	<script>
		var activeLang = <?php echo json_encode($activeLang);?>;
		$('.locfields').parent().parent().hide();
		$('.locfields'+activeLang).parent().parent().show();
		$(document).ready(function(){
			common.initTinyMCE();
			contentVersion.init();
		});
	</script>

</div>