<?php
	$this->headTitle(_('Email templates'));
	$this->headScript()->appendFile(URL . 'js/admin/adminGrid.js');
?>

<div id="gridbox"></div>
<div style="display:none">
	<div id="name_flt_box"><input class="js-filter-value" onkeyup="adminGrid.filterBy()"></div>
</div>

<script>
	$(document).ready(function(){ 
		adminGrid.init({
			listUrl: <?php echo json_encode($this->basePath('admin/template/list'));?>+"?action=list",
			columns: [
				{'title' : "#", 'width': 15},
				{'title' : <?php echo json_encode(_('Id'));?>, 'width': 25, 'colSorting': 'int'},
				{'title' : <?php echo json_encode(_('Name'));?>, 'width': 225, 'colSorting': 'str',
					'filter': {
						'sourceContainerSelector': "#name_flt_box",
						'values': [{'name':'flName'}]
					}
				},
				{'title' : <? echo json_encode(_('Actions'));?>, 'width': 30},
			],
			events: [
				{
					'name': "onBeforeSelect", 'callback': function(id,ind){
						var rowNum = adminGrid.grid.cellById(id,0).getValue();
						return common.selectItemInList(id, rowNum, <?=json_encode($this->basePath('admin/template/edit/'));?>, true);
					}
				}
			]
		});
	});
</script>