<?php
header("Content-Type: text/xml");
?>
<rows pos="<?php echo $pos;?>" total_count="<?php echo $total;?>">
	<?php
	$i=$pos;

	foreach($list as $item) {
		$i++;
		$editActions = "<a class='edit' href='#'>" . _("Edit") . "</a> ";
		?>
		<row id='<?php echo $item->id;?>'>
			<cell><?php echo $i;?></cell>
			<cell><?php echo $item->id;?></cell>
			<cell><?php echo htmlspecialchars($item->name);?></cell>
			<cell><?php echo htmlspecialchars($editActions);?></cell>
		</row>
		<?php } ?>
</rows>