<?php if (!empty($error)) { ?>
	<p><?php echo htmlspecialchars($error);?></p>
	<?php } ?>
<?php
	$this->headLink()->prependStylesheet($this->basePath() . '/css/pages/login.css');
?>
<fieldset>
	<a class="hybridauth" href="<?php echo $this->url('auth/google');?>">Login with Google+</a><br/>
	<a class="hybridauth" href="<?php echo $this->url('auth/facebook');?>">Login with Facebook</a>
</fieldset>
OR
<?php
	echo $this->wrappedForm($form);
?>
<a href="<?php echo URL.'auth/forgotpassword';?>">Forgot password?</a>
