<?php
$this->myviewalias()->prepareControllerAction();
$controller = $this->controller;

$role = $this->getUser()->getRole();
?>
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name = "format-detection" content = "telephone=no">
		<?php echo $this->headTitle(SITE_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>
		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile(URL. 'js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery-2.1.1.min.js')
    ; ?>

    </head>
    <body>
    	<div id="wrap">
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo URL; ?>"><img src="<?php echo $this->basePath('images/logo.png') ?>"/></a>
                </div>
                <div class="bs-component">
										<ul class="nav nav-pills">
                        <li class="<?=in_array($controller, array('Index'))?"active ":''?>"><a href="<?php echo URL; ?>"><?php echo _('Home') ?></a></li>
                        <?php if ($this->getUser()->getId()) { ?>
                        	<li><a href="<?php echo URL.'user/logout'; ?>" class=""><span><?echo _('Logout');?></span></a></li>
                        <? } else { ?>
                        	<li class="<?=in_array($controller, array('User'))?"active ":''?>"><a href="<?php echo URL.'user/login'; ?>"><span><?echo _('Login');?></span></a></li>
                        <?php } ?>
                        <? if ($this->getUser()->isAllowed('Admin\Controller\User', 'index')) {?>
													<li><a href="<?php echo $this->basepath('admin/')?>" class=""><span><?echo _('Admin panel');?></span></a></li>
												<?}?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
      </div>
      <div id="footer">
				<div class="container">
					<hr>
				  <p><?php printf(_('&copy; %d by CodeIT. All rights reserved.'), date('Y')) ?></p>
				</div>
      </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
