<?php 
	$this->headTitle(_('Login'));
?>
<div class="header-title ipadpages">
	<div class="h-bg">	
		<h1><?php echo _('Reset password') ?></h1>
	</div>
</div>
<div class="content-border login">
	<div class="login-form">
	<?php if ($success) {
	 echo _('Please check your email for instructions to activate new password');
	 return true;
	} ?>
	<?php
	if (isset($err) && !empty($err)){
		echo '<div class="error top_error">'.$err.'</div>';
	}
	echo $this->wrappedForm($form);
	?>
	</div>
</div>