<h1><?php echo _('Welcome to CodeIT Carcass!'); ?></h1>
<p class="lead"><?php echo _('Corporate framework which contains the best and proven achievements of CodeIT');?></p>

<div class="row">
	<div class="col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo _('CodeIT Carcass documentation') ?></h3>
			</div>
			<div class="panel-body">
				<p><?php echo _('Article which describes project structure'); ?></p>
				<p><a class="btn btn-default pull-right" href="http://wiki.codeit.com.ua/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F_CodeIT_Carcass" target="_blank"><?php echo _('Read Wiki article') ?> &raquo;</a></p>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo _('Zend Framework 2 documentation') ?></h3>
			</div>
			<div class="panel-body">
				<p><?php echo _('Programmer’s Reference Guide of Zend Framework 2'); ?></p>
				<p><a class="btn btn-default pull-right" href="http://framework.zend.com/manual/current/en/index.html" target="_blank"><?php echo _('Read guide') ?> &raquo;</a></p>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo _('Admin panel interface') ?></h3>
			</div>
			<div class="panel-body">
				<p><?php echo _('Company design, user friendly interface');?> </p>
				<p><a class="btn btn-default pull-right" href="<?php echo URL;?>admin" ><?php echo _('Go to admin panel') ?> &raquo;</a></p>
			</div>
		</div>
	</div>
</div>
