<div class="jumbotron">
    <h1><?php echo _('Welcome to CodeIT Carcass!'); ?></h1>
</div>

<div class="row">
		<div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo _('CodeIT Carcass documentation') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo _('Article which describes project structure'); ?></p>
                <p><a class="btn btn-default pull-right" href="#" target="_blank"><?php echo _('Read Wiki article') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
	
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo _('Solutions for Zend Framework 2') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo _('Base classes to inherite controllers and models: AppController and AppTable'); ?></p>
                <p><a class="btn btn-default pull-right" href="http://wiki.codeit.com.ua/index.php/%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F_%D0%B4%D0%BB%D1%8F_Zend_Framework_2" target="_blank"><?php echo _('Read Wiki article') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo _('Admin panel interface') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo _('Company design, user friendly interface');?> </p>
                <p><a class="btn btn-default pull-right" href="<?php echo URL;?>admin" ><?php echo _('Go to admin panel') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
