<div class="jumbotron">
    <h1><?php echo _('Welcome to base project by codeIT!'); ?></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo _('Solutions for Zend Framework 2') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo _('Base classes to inherite controllers and models: AppController and AppTable'); ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo _('Read Wiki article') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo _('Admin panel interface') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo _('Company design, user friendly interface');?> </p>
                <p><a class="btn btn-success pull-right" href="<?php echo URL;?>admin" ><?php echo _('Go to admin panel') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
